# CTP (中国期货市场) 配置

# 经纪商ID
broker_id: "9999"

# 投资者ID (账号)
investor_id: "000000"

# 密码
password: "your_password_here"

# 行情前置地址 (SimNow 24小时环境)
md_address: "tcp://180.168.146.187:10131"

# 交易前置地址 (SimNow 24小时环境)
td_address: "tcp://180.168.146.187:10130"

# 应用ID (穿透式监管,可选)
app_id: ""

# 认证码 (穿透式监管,可选)
auth_code: ""

# 用户产品信息
user_product_info: "nof0"

# 是否启用模拟模式 (true=不连接真实CTP, false=连接真实CTP)
mock_mode: true
# ==========================================
# 说明:
# ==========================================
#
# 1. SimNow 环境 (测试用):
#    - 24小时环境:
#      MD: tcp://180.168.146.187:10131
#      TD: tcp://180.168.146.187:10130
#    - 交易时段环境:
#      MD: tcp://180.168.146.187:10211
#      TD: tcp://180.168.146.187:10201
#
# 2. 生产环境:
#    请联系您的期货公司获取:
#    - broker_id (经纪商代码)
#    - md_address (行情地址)
#    - td_address (交易地址)
#    - app_id & auth_code (穿透式监管)
#
# 3. mock_mode:
#    - true: 使用内置模拟数据,不连接CTP
#    - false: 连接真实CTP服务器
#
# 4. 安全提示:
#    - 不要将包含真实密码的配置文件提交到版本控制
#    - 生产环境建议使用环境变量或密钥管理服务
